# Request absolute movements of the robot
# The robot will move to the specified absolute position
# The rotations are performed around the robot's current orientation and before any translation
float64 x # x-axis absolute position in millimeters
float64 y # y-axis absolute position in millimeters
float64 z # z-axis absolute position in millimeters
float64 rx_deg  # roll angular absolute position in degrees
float64 ry_deg  # pitch angular absolute position in degrees
float64 rz_deg  # yaw angular absolute position in degrees
int32 speed_percent # max speed of the movement as a percentage of maximum speed
int32 time_to_top_speed_ms # time to reach top speed in milliseconds
string frame # the frame of reference for the movement, e.g., "base_link", "odom", etc.
---
# Result
bool goal_reached # true if the goal was reached
---
# Feedback containing the status of the relative motion
string motion_id # the ID of the motion command
string status
# TODO(@yguel): add the following fields to the feedback
# float64 x_error # x-axis error in millimeters
# float64 y_error # y-axis error in millimeters
# float64 z_error # z-axis error in millimeters
# float64 rx_error # roll angular error in degrees
# float64 ry_error # pitch angular error in degrees
# float64 rz_error # yaw angular error in degrees
# string error_frame # the frame of reference for the error, e.g., "base_link", "odom", etc.